package io.github.diegoflassa.teste_android_kotlin.buildsrc

object Versions {
    const val ktlint = "0.41.0"
    const val kotlin_compiler_version = "1.5.30-M1"
    const val gradle = "7.1.0-alpha03"
    const val coil = "1.3.0"
    const val data_store = "1.0.0-rc01"
    const val gson = "2.8.7"
    const val retrofit = "2.0.0"
    const val retrofit_adapter = "2.9.0"
    const val converter = "2.9.0"
    const val converter_jackson = "2.9.0"
    const val jackson = "2.13.0-rc1"
    const val dagger = "2.38"
    const val hilt = "2.38"
    const val rxjava = "3.0.13"
    const val rxandroid = "3.0.0"
    const val material = "1.5.0-alpha01"
	const val koin = "3.1.2"
    const val koin_ext = "3.0.2"
    const val play_core = "1.8.1"
    const val activity_ktx = "1.3.0-rc02"
    const val annotation = "1.3.0-alpha01"
    const val appcompat = "1.4.0-alpha03"
    const val constraintlayout = "2.1.0-beta02"
    const val core_ktx = "1.7.0-alpha01"
    const val fragment_ktx = "1.4.0-alpha04"
    const val lifecycle = "2.4.0-alpha02"
    const val navigation = "2.4.0-alpha04"
    const val preference_ktx = "1.1.1"
    const val recyclerview = "1.2.1"
    const val recyclerview_selection = "1.2.0-alpha01"
    const val databinding = "7.1.0-alpha03"
    const val core = "1.4.0"
    const val espresso = "3.4.0"
    const val test = "1.4.0"
    const val junit_ktx = "1.1.3"
    const val safeargs_plugin = "2.4.0-alpha04"
    const val spotless = "5.8.2"
    const val junit = "4.13.2"
    const val workVersion = "2.7.0-alpha04"
}